# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT miavbackend.wsgi

beta_settings:
    cloud_sql_instances: cs5356-miav:us-east1:kvd-miav

runtime_config:
  python_version: 3
# [END runtime]
