# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import miavapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('num_boxes', models.IntegerField()),
                ('description', models.TextField()),
                ('job_type', models.CharField(max_length=4, validators=[miavapp.validators.validate_job_type])),
                ('status', models.CharField(max_length=10, validators=[miavapp.validators.validate_status])),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='miavapp.Driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Passenger')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc_lat', models.FloatField()),
                ('start_loc_long', models.FloatField()),
                ('end_loc_lat', models.FloatField()),
                ('end_loc_long', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Driver')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Job')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('phone', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miavapp.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Passenger'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miavapp.User'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Vehicle'),
        ),
    ]
