# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0002_auto_20171115_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location_long',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='miavapp.Vehicle'),
        ),
    ]
