# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0003_auto_20171115_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location_long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miavapp.Vehicle'),
        ),
    ]
