# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0004_auto_20171119_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
