# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0005_auto_20171119_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
