# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0007_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
