# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miavapp', '0008_auto_20171206_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_loc_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_loc_long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
